### ISSUE TITLE
Reference curves for skin friction coefficient

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/wall_modeling#7]
Hi Jihoo,
let's clear the doubts we have about the different c_f reference curves. I have digitized and uploaded Wieghardts c_f measurements for the flat plate without pressure gradient to the cloud folder. Next, I suggest the following:
- plot the experimental data against the Reynolds number instead of x; curve 1 and 2 are the curves for U=17.8m/s and 33.0m/s, respectively; the kinematic viscosity needs to be extracted from Wieghardts article
- plot eq. 26 from [this reference](https://link.springer.com/content/pdf/10.1007%2F978-3-662-11836-8_50.pdf) for comparison
- plot the correlation we have used so far for comparison
- use the generic equation c_f = m / (log(Re)+p)^n, and try to find optimal values for m, p, and n; I suggest a simple brute force approach:
  - as metric you compare against the experimental data and compute the L2 norm
  - create arrays for m, p, and n ranging around the values given in eq. 26
  - loop over all permutations and select the one giving the lowest L2 error with respect to the experiments

If questions come up, simply reply here.

Best, Andre

**Comment by JihooKang-KOR** [comment]
Dear Andre,

I made draft plots for reference curves in a jupyter notebook. However, first of all, I would like to check how the generic equation behaves depending on m, p, and n values. Thus, I used a regression method this time instead of a simple brute force method.

After investigating the behavior, there are some findings as follows;
1. The values m, p, and n strongly depend on each initial value, and therefore the final values vary (a lot of local minima).
2. Those local minima have similar cost values approximately 3.5e-8, and the shapes of the graph are quite similar as well.
3. Due to the above two reasons, I am not sure if the brute force approach works or not. The shape will not dramatically be distinguishable among them.

The distinguishable part should be the very front part of the plate. However, we can see this part only in *Wieghardt* curve in **OpenFOAM** as follows. This steep slope can be a decisive factor for determining m, p, and n, but there is no experimental data for the region. The other plots are in the notebook '*RefCurves_Cf.ipynb*'.

![image](https://user-images.githubusercontent.com/75588742/118730614-357d1000-b838-11eb-9d0e-0548f4e663c3.png)

I would like to report that this is the current situation for the reference curves for skin friction.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,
thanks for the update. I expected there to be many local minima, which is why I suggested brute-forcing the optimal solution instead of using something like a Newton method. The exact parameters for the reference curve are not really that important. Ultimately, agreement with the experimental results is what counts the most when looking at our numerical results. A hint for the plot above: if you visualize experimental data (or any other discrete data source), please use `scatter` instead of `plot`.
Best, Andre
